### ISSUE TITLE
Template name validation on create

### ISSUE THREAD

**Issue by dworac** [dworac/cli#46]
when a project is created the "-t" flag should not be  optional and should be checked if it exists instead of just throwing:

Error: ENOENT: no such file or directory, scandir 'C:\Users\Dworak\Documents\Repos\@dworac\cli\templates\typescript-worke'
    at Object.readdirSync (node:fs:1442:3)
    at ut (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:23:1514)
    at R.ur (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:23:2424)
    at R.t [as _actionHandler] (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:14:482)
    at C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:2841
    at R._chainOrCall (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:1454)
    at R._parseCommand (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:2817)
    at C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:475
    at R._chainOrCall (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:1454)
    at R._dispatchSubcommand (C:\Users\Dworak\Documents\Repos\@dworac\cli\dist\index.js:17:378) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Dworak\\Documents\\Repos\\@dworac\\cli\\templates\\typescript-worke'
}

**Comment by dworac** [comment]
Issue has been resolved when refactoring the code
